### ISSUE TITLE
coord_30.csv usage

### ISSUE THREAD

**Issue by mhmadayad** [BrotherJing/RNN_tabletennis#3]
if I am using coord_30.csv data file , then the configuration is:
`else:
	config['seq_len'] = 70#29
	config['batch_size'] = 20
	config['overlap_rate'] = 0.0
	config['lr_decay'] = 0.9
	config['max_epoch'] = 10
	config['max_max_epoch'] = 15`

Why config['seq_len'] = 70#29 ? shouldn't it be 30 ?

there is a run time error as well. Is the project working without any bugs ?

**Comment by BrotherJing** [comment]
Sorry.. I should have cleaned that part. `config['seq_len']` should be less than or equal to the length of the trajectory in your data. for `coord_30.csv` 30 is fine.
