### ISSUE TITLE
What is the expected output and the breakpoint?

### ISSUE THREAD

**Issue by mhmadayad** [BrotherJing/RNN_tabletennis#5]
After the training the model, are you predicting a trajectory or just classifying trajectories ?
If you are prediciting trjacetories then you are feeding only starting point and timestep and the output should be the whole trajectory. But there should be a goal point or a  break point to tell our model where to stop, right ?

**Comment by BrotherJing** [comment]
Yes you're right. Actually this project is part of my bachelor thesis and it aims to predict the landing point of the ball on the table. In the code I just set predicting length identical to length in training data.
